name: Flat
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./xml_postprocessing.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v3.5.3
      - name: Fetch TXT
        uses: githubocto/flat@v3.4.0
        with:
          http_url: https://www.cnb.cz/cs/financni-trhy/devizovy-trh/kurzy-devizoveho-trhu/kurzy-devizoveho-trhu/denni_kurz.txt
          downloaded_filename: denni_kurz.txt
      - name: Fetch and postprocess XML
        uses: githubocto/flat@v3.4.0
        with:
          http_url: https://www.cnb.cz/cs/financni-trhy/devizovy-trh/kurzy-devizoveho-trhu/kurzy-devizoveho-trhu/denni_kurz.xml
          downloaded_filename: denni_kurz.xml
          postprocess: ./xml_postprocessing.ts
